---
abstract: 'Schema versioning for DBIx::Class with version information embedded inline in the schema definition.'
author:
  - 'Peter Mottram (SysPete) <peter@sysnix.com>'
build_requires:
  DBD::SQLite: '1.4'
  DBIx::Class::Schema::Loader: '0.0704'
  File::Spec: '3.47'
  Test::Most: '0.33'
  Test::Roo: '1.003'
  Test::Warnings: '0.012'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Class-Schema-Versioned-Inline
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Class: '0.0827'
  SQL::Translator: '0.11018'
  Try::Tiny: '0.18'
  perl: '5.006'
  version: '0.9902'
resources:
  bugtracker: https://github.com/Sysnix/dbix-class-schema-versioned-inline/issues
  repository: https://github.com/Sysnix/dbix-class-schema-versioned-inline.git
version: '0.004'
